### ISSUE TITLE
[ISSUE] Hornet - HSI Warning Altitude RADAR

### ISSUE THREAD

**Issue by HILOK** [the-paid-actor/dcs-dtc#24]
just noticed, the DTC/Misc/Radar ALT setting will set the radar altimeter (analogue gauge right knee) instead of the HSI>DATA>A/C>WARN ALT>RADAR. dont know, if this was a mistake. anyway, would love to have an option for the mentioned HSI radar altitude warning. there may be a DCS bug though that currently prevents that setting with WOW...but maybe there is a workaround ?

**Comment by p-louis** [comment]
That behavior is indeed intentional. I originally intended to add setting the HSI>DATA...-Option as well, but as you've already noticed this is not functional in DCS at the moment. For this reason I left it out and added setting the MDA on the radar altimeter instead.
Should the DCS bug be resolved some time in the future it's a minor effort to add this functionality as well.
