### ISSUE TITLE
[BUG] FA18 Radio Preset not loaded

### ISSUE THREAD

**Issue by Heater711** [the-paid-actor/dcs-dtc#28]
RADIO 1 presets it seems done, RADIO 2 presets are not loaded very well.

**Comment by p-louis** [comment]
Could you elaborate what the issue with the radio-2 entry consists of? Specifically if the problem occurs on data entry of frequencies or whether there is another issue like an offset of the channels set.

In the first case, my suggestion is to try and increase the CommandDelayMs value inside the `dtc-settings.json` that should solve errors on data entry that may occur due to client-'lag'. Besides that you need to have channel 1 selected on both radios when pressing the upload button to ensure the channels are set correctly.

**Comment by p-louis** [comment]
Fixed in RC8
