### ISSUE TITLE
Pre Planned Coordinates 

### ISSUE THREAD

**Issue by amn2be** [the-paid-actor/dcs-dtc#36]
Pre Planned Coordinates do not work. Constant errors across the board for the gps bombs. Can not figure out why all stations were pre set in PP and the fusing set properly.

**Comment by p-louis** [comment]
> all stations were pre set in PP
That seems to be the issue here. Uploading relies on the settings being in default state, meaning TOO mode being set. The fusing should not have an impact on the upload process.

Should you still run into errors on data-entry, I'd suggest to increase the key-press delay in the dtc-settings.json file.

**Comment by p-louis** [comment]
If you have issues with data-entry then you should increase it, 500 is a value I've heard works for most people that faced such issues

**Comment by amn2be** [comment]
just did it still getting errors set all stations to too and left it alone

**Comment by amn2be** [comment]
wish i could show you this tool is so great sorry to be a pain

**Comment by amn2be** [comment]
i sent a dm in discord as well rayburge

**Comment by p-louis** [comment]
Do you have any way to do a screen-recording?
The discord-dm probably went to the-real-actor, not me; at least I didn't receive any :) 
my discord is Fuzzel#8473

**Comment by amn2be** [comment]
Request via DM sent Discord
